version: 2.1
orbs:
  node: circleci/node@4.2.0
workflows:
  build_and_test:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 14.16.0
                - 12.21.0
                - 10.24.0
